# Generated by Django 3.1.4 on 2020-12-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactadmindata',
            old_name='username',
            new_name='user_name',
        ),
    ]
