# Generated by Django 3.1.4 on 2020-12-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blogsmodel_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='num_of_saves',
            field=models.IntegerField(default=0),
        ),
    ]
