# Generated by Django 3.1.4 on 2020-12-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/aboutme/%Y/%m/%d/')),
                ('description', models.CharField(max_length=255)),
                ('insta_link', models.CharField(max_length=255)),
                ('linkedin_link', models.CharField(max_length=255)),
                ('github_link', models.CharField(max_length=255)),
                ('website_link', models.CharField(max_length=255)),
            ],
        ),
    ]
