# Generated by Django 3.1.4 on 2020-12-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
