# Generated by Django 3.1.4 on 2020-12-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20201212_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmeinfo',
            name='address',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutmeinfo',
            name='email',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutmeinfo',
            name='phone',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
